{
 "title": "osf",
 "description": "Dashboard for official Prometheus Python Client's metrics",
 "tags": [
  "flask",
  "app",
  "web",
  "python"
 ],
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   { "name": "datasource", "query": "prometheus" },
   {
    "name": "interval",
    "query": "1m,10m,30m,1h,6h,12h,1d,7d,14d,30d"
   },
   {
    "name": "pod",
    "label": "Pod name",
    "query": "label_values(python_gc_objects_collected_total, pod)"
   },
   { "name": "percentile", "label": "Percentile", "query": "100,99,95,90,75,50,25" }
  ]
 },
 "panels": [
  {
   "title": "CPU usage",
   "type": "graph",
   "gridPos": { "h": 9, "w": 8, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "rate(process_cpu_seconds_total{pod=~\"$pod\"}[$interval])",
     "legendFormat": "cpu"
    }
   ]
  },
  {
   "title": "Memory usage",
   "type": "graph",
   "gridPos": { "h": 9, "w": 8, "x": 8, "y": 0 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "process_resident_memory_bytes{pod=~\"$pod\"}",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Open File Descriptors",
   "type": "graph",
   "description": "Number of open file descriptors",
   "gridPos": { "h": 9, "w": 8, "x": 16, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "(process_open_fds{pod=~\"$pod\"})",
     "legendFormat": "{{ pod }}"
    }
   ]
  },
  {
   "title": "Pod's Uptime - $pod",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 24, "x": 0, "y": 9 },
   "repeat": "pod",
   "format": "s",
   "valueName": "current",
   "targets": [
    {
     "expr": "(time() - process_start_time_seconds{pod=~\"$pod\"})"
    }
   ]
  },
  {
   "title": "Pod's App Version -  $pod",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 24, "x": 0, "y": 12 },
   "repeat": "pod",
   "format": "none",
   "valueName": "name",
   "targets": [
    {
     "expr": "app_version_info{pod=~\"$pod\"}",
     "legendFormat": "{{ version }}"
    }
   ]
  },
  {
   "title": "Pod's App Config  - $pod",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 24, "x": 0, "y": 15 },
   "repeat": "pod",
   "format": "none",
   "valueName": "name",
   "targets": [
    {
     "expr": "app_version_info{pod=~\"$pod\"}",
     "legendFormat": "{{ config }}"
    }
   ]
  },
  {
   "title": "Pod's Python Version  - $pod",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 24, "x": 0, "y": 18 },
   "repeat": "pod",
   "format": "none",
   "valueName": "name",
   "targets": [
    {
     "expr": "python_info{pod=~\"$pod*\"}",
     "legendFormat": "{{ implementation }} {{ version }}"
    }
   ]
  }
 ]
}